# Generated by Django 4.0.3 on 2022-03-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=50)),
                ('tumori', models.CharField(max_length=50)),
                ('features', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
